// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejh0vnKQPf9EnwiE2xZOoS0AP6POwpCI',
    appId: '1:228355810133:web:e52ccd3500c0c8a30a85dc',
    messagingSenderId: '228355810133',
    projectId: 'studio-pro-825c5',
    authDomain: 'studio-pro-825c5.firebaseapp.com',
    storageBucket: 'studio-pro-825c5.firebasestorage.app',
    measurementId: 'G-JDR22XN18X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGfamFE6TNpBzpe_vILY6CUlgASDiyF6w',
    appId: '1:228355810133:android:e96232efcc105e850a85dc',
    messagingSenderId: '228355810133',
    projectId: 'studio-pro-825c5',
    storageBucket: 'studio-pro-825c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdyI1uST8tqXMZQNxuZzLtA50lUufhIg',
    appId: '1:228355810133:ios:43e596f868d72dd10a85dc',
    messagingSenderId: '228355810133',
    projectId: 'studio-pro-825c5',
    storageBucket: 'studio-pro-825c5.firebasestorage.app',
    iosBundleId: 'com.example.belezaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdyI1uST8tqXMZQNxuZzLtA50lUufhIg',
    appId: '1:228355810133:ios:43e596f868d72dd10a85dc',
    messagingSenderId: '228355810133',
    projectId: 'studio-pro-825c5',
    storageBucket: 'studio-pro-825c5.firebasestorage.app',
    iosBundleId: 'com.example.belezaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCejh0vnKQPf9EnwiE2xZOoS0AP6POwpCI',
    appId: '1:228355810133:web:31a2f7ae63b902290a85dc',
    messagingSenderId: '228355810133',
    projectId: 'studio-pro-825c5',
    authDomain: 'studio-pro-825c5.firebaseapp.com',
    storageBucket: 'studio-pro-825c5.firebasestorage.app',
    measurementId: 'G-D1SC7GHN9J',
  );
}
